feat: create layout bubble and interract with it
dis-moi/mobile_poc pull request #17
Opened 2021-02-25 16:30 UTC by felix-lambert

Because it's a POC and because of some conversations with my friends/colleagues I've decided to stop atomic commits. We could try this method again after the POC

2021-02-26 12:13 UTC, lutangar requested changes

2021-02-26 14:48 UTC, lutangar commented on android/app/src/main/AndroidManifest.xml
> +  package="com.dismoi_poc">
After more inquiries and a discussion with @tobika he pointed out that once publish this id can't be changed, so it must be chosen carefully and not mess with the expected production id. It also appears in shop URL so it does matters.

For convention see this file:
> https://developer.android.com/guide/topics/manifest/manifest-intro
> `example` can be a company name for example

Ours could be something like :
- `com.dismoi.app.poc` for the PoC
- `com.dismoi.app` for production

You should look for (and replace) other occurrences that I probably missed.

2021-03-15 11:15 UTC, felix-lambert commented on android/app/src/main/res/values/strings.xml
> +  <string name="app_name">dismoi</string>
Ok I will just put `dismoi` if it's fine for you

2021-03-15 11:18 UTC, lutangar commented on android/app/src/main/res/values/strings.xml
> +  <string name="app_name">dismoi</string>
Check out my other comment:
https://github.com/dis-moi/mobile_poc/pull/17#discussion_r583690887

2021-03-15 11:31 UTC, felix-lambert commented on android/app/src/main/AndroidManifest.xml
> +  package="com.dismoi_poc">
I propose to put the following
```
com.dismoi
```
If we want to make a contribution app we can put:
```
com.dismoi.contribution
```
And a bubble layout app:
```
com.dismoi.scout
```
Or other suggestions?
Basically it should be: com.companyname.applicationname
https://stackoverflow.com/questions/6273892/android-package-name-convention

Happy to have suggestions here. I don't think we need to put app. Because I suspect google play using the package name as one of the keys for the search engine.

2021-03-15 12:04 UTC, felix-lambert commented on app.json
> +  "name": "dismoi_poc",
I'm going to put here:

`dismoi_mobile` like to be coherent with `dismoi-webextension`

2021-03-15 12:55 UTC, lutangar commented on android/app/src/main/res/values/strings.xml
> +  <string name="app_name">dismoi</string>
> Ok I will just put dismoi if it's fine for you

:+1:

2021-03-15 12:58 UTC, lutangar commented on android/app/src/main/AndroidManifest.xml
> +  package="com.dismoi_poc">
Either `com.dismoi.contribution` or `com.dismoi.scout` sounds fine by me.

> Also I propose to remove poc because it will never be deployed to google play.

Alright!

2021-03-15 18:06 UTC, lutangar reviewed
Is this ready for review? I actually saw you added prettier, but I don't it has be run anywhere.

2021-03-15 18:12 UTC, felix-lambert commented on package.json
> +  "name": "dismoi-mobile",
Why not but in the package.json file of the extension I saw `dismoi-webextension`. 

https://github.com/dis-moi/extension/blob/master/package.json#L2

I'm wondering if it's not better to be coherent, or it doesn't really matter?

2021-03-15 18:14 UTC, lutangar commented on package.json
> +  "name": "dismoi-mobile",
Agreed, I can propose this change later on as a global change on packages org namespace.

2021-03-15 18:17 UTC, felix-lambert commented on package.json
> +  "name": "dismoi-mobile",
Cool maybe we can open a new issue to tackle this subject

2021-03-16 09:45 UTC, felix-lambert commented
@lutangar just tested `lint-staged` by doing a new commit it works well. You can review

2021-03-16 10:07 UTC, lutangar commented on index.js
>  import {AppRegistry} from 'react-native';
> just tested lint-staged by doing a new commit it works well. You can review

Alright, but theses files are already committed and should also be prettified. You may do that in another PR if you prefer.

2021-03-16 10:07 UTC, lutangar approved these changes

2021-03-16 10:25 UTC, merged