feat: only fetch and consider matching contexts for subscribed contributors
dis-moi/mobile_poc pull request #257
Opened 2021-10-01 14:38 UTC by JalilArfaoui

closes #249

2021-10-08 09:13 UTC, JalilArfaoui commented
@lutangar you’ve always been soooooo long to review 🙃 ;-)

2021-10-21 07:40 UTC, JalilArfaoui commented
@lutangar 😘

2021-10-29 15:33 UTC, lutangar requested changes

2021-10-29 15:33 UTC, lutangar commented on android/app/src/main/java/com/dismoi/scout/accessibility/BackgroundService.kt
> +    client.newCall(request).enqueue(object : Callback {
Is there Kotlin CS Linter/Fixer?
This seems inconsistent with the rest of the file.

2021-10-29 15:33 UTC, lutangar commented on android/app/src/main/java/com/dismoi/scout/accessibility/BackgroundService.kt
> +    val matchingContextsEndpoint: String = "https://notices.bulles.fr/api/v3/matching-contexts?$matchingContextsQueryString"
> TODO to be moved to env configuration
 
 :+1:

2021-10-29 15:33 UTC, lutangar commented on android/app/src/main/java/com/dismoi/scout/accessibility/BackgroundService.kt
> +    // TODO URL should be composed here
You're not adding contributor ids anymore? Thought it was the purpose of this PR.

2021-10-29 15:39 UTC, JalilArfaoui commented on android/app/src/main/java/com/dismoi/scout/accessibility/BackgroundService.kt
> +    // TODO URL should be composed here
@lutangar it’s already in `matchingContextsQueryString` … The whole querystring with ids has already been saved in preferences on subscription 🙈 

The commented code is what I’d like to do once we just save contributors IDs :-)

2021-10-29 15:44 UTC, JalilArfaoui commented on android/app/src/main/java/com/dismoi/scout/accessibility/BackgroundService.kt
> +    client.newCall(request).enqueue(object : Callback {
I use Android Studio with Kotlin Style Guide …

I’ve just checked and in this particuliar syntax, the linter insist to have a space …

Found source here :

> Put a space before : in the following cases:    after the object keyword

https://kotlinlang.org/docs/coding-conventions.html#colon

2021-10-29 15:46 UTC, JalilArfaoui commented on android/app/src/main/java/com/dismoi/scout/accessibility/BackgroundService.kt
> +    // TODO URL should be composed here
Does it answer your question @lutangar ?

2021-10-29 15:56 UTC, lutangar commented on android/app/src/main/java/com/dismoi/scout/accessibility/BackgroundService.kt
> +    // TODO URL should be composed here
Let's say it does... I suppose now is not time to change this.

2021-10-29 16:33 UTC, merged