Feat/redirect to dis moi app
dis-moi/mobile_poc pull request #36
Opened 2021-03-25 17:09 UTC by felix-lambert

When i enable accessibility service the dismoi app should be launched automatically

2021-03-26 09:13 UTC, lutangar commented
Too many styles diff, quite difficult to review in this state, maybe chang the target branche and rebase?

2021-03-26 09:16 UTC, felix-lambert commented
Maybe review first: 
https://github.com/dis-moi/mobile_poc/pull/31
Then:
https://github.com/dis-moi/mobile_poc/pull/35
And then:
https://github.com/dis-moi/mobile_poc/pull/36

2021-03-26 09:19 UTC, lutangar commented
> Maybe review first:

If we do this, not only I have to review but we'll have to merge before moving on to the next review, I'd rather change targeted branch if they are dependent on each others

2021-03-26 10:09 UTC, felix-lambert commented
#36 is an evolution of #35 so didn't want to put on the same target branch to avoid conflicts.
#31 is independent so has the same target branch as #35

2021-03-26 12:54 UTC, lutangar requested changes

2021-03-26 12:54 UTC, lutangar commented on android/app/src/main/java/com/dismoi/scout/Floating/Layout/Base.java
> +  public void create(WindowManager getWindowManager, WindowManager.LayoutParams layoutParams, Coordinator layoutCoordinator) {
This looks like a constructor and the job of a constructor, so it's should probably one.

2021-03-26 12:54 UTC, lutangar commented on android/app/src/main/java/com/dismoi/scout/Floating/Layout/Bubble.java
> +  private class MoveAnimator implements Runnable {
I'm pretty sure I arleady reviewed that somewhere :thinking:

2021-03-26 12:54 UTC, lutangar commented on android/app/src/main/java/com/dismoi/scout/Floating/Layout/Trash.java
> +  public static final int VIBRATION_DURATION_IN_MS = 70;
Love those meaningful namings <3

2021-03-26 12:54 UTC, lutangar commented on android/build.gradle
> +        // classpath 'com.github.dcendents:android-maven-plugin:1.2'
Still relevant?

2021-03-26 12:54 UTC, lutangar commented on android/build.gradle
> +    // allprojects {
Still relevant?

2021-03-26 12:54 UTC, lutangar commented on android/settings.gradle
> +//, ':bubbles'
Still relevant?

2021-03-29 08:54 UTC, felix-lambert commented on android/app/src/main/java/com/dismoi/scout/Floating/FloatingModule.java
> +    messageDisMoiView.setOnBubbleRemoveListener(new Message.OnBubbleRemoveListener() {
I'm not sure I'm getting this very well. Can you show me some code example?

2021-03-29 08:57 UTC, felix-lambert commented on android/app/src/main/java/com/dismoi/scout/Floating/FloatingModule.java
> +  public FloatingModule(ReactApplicationContext reactContext) {
Code example or new PR would be great

2021-03-29 08:59 UTC, lutangar commented on android/app/src/main/java/com/dismoi/scout/Floating/FloatingModule.java
> +    messageDisMoiView.setOnBubbleRemoveListener(new Message.OnBubbleRemoveListener() {
I don't have an example but I supposed  (maybe wrongly) :
```
      public void onBubbleRemoved(Message bubble) {
        messageDisMoiView = null;
        sendEventToReactNative("floating-dismoi-message-remove");
      }
```
...could possibly be defined once in the class.

If not posible just ignored this.

2021-03-29 09:27 UTC, lutangar commented on android/app/src/main/java/com/dismoi/scout/Floating/FloatingService.java
> +      windowManager = (WindowManager)getSystemService(WINDOW_SERVICE);
Usually we instantiate once in constructor, so you don't have to check if `windowManager == null` here.
But might be different usecase here, ignore my comment if not relevant.

2021-03-29 09:28 UTC, lutangar commented on android/app/src/main/java/com/dismoi/scout/Floating/FloatingModule.java
> +  public FloatingModule(ReactApplicationContext reactContext) {
I'd love to dig on this, but I probably won't have the time, so just ignore this.

2021-03-29 13:55 UTC, lutangar approved these changes

2021-03-29 13:55 UTC, merged